version: 2
jobs:
  blank-job:
    docker:
      - image: 'circleci/node:10-stretch'
    working_directory: ~/repo
    environment:
      TERM: dumb
    steps:
    - run: "echo OK"
workflows:
  version: 2
  blank-job-exec:
    jobs:
      - blank-job:
          filters:
            branches:
              only: gh-pages
